<?php

namespace ContainerEZKtkqD;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KYedUCbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kYedUCb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kYedUCb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'reg' => ['services', 'doctrine', 'getDoctrineService', false],
            'repo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'reg' => '?',
            'repo' => 'App\\Repository\\UserRepository',
        ]);
    }
}
