<?php

namespace ContainerIZ85uJU;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OPHNw6zService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OPHNw6z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OPHNw6z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repo' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService', true],
            'res' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'repo' => 'App\\Repository\\ProductRepository',
            'res' => '?',
        ]);
    }
}
