<?php

namespace ContainerE1Kb8Kr;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5PAIovCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5PAIovC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5PAIovC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'res' => ['services', 'doctrine', 'getDoctrineService', false],
            'shop' => ['privates', 'App\\Repository\\ShopRepository', 'getShopRepositoryService', true],
        ], [
            'res' => '?',
            'shop' => 'App\\Repository\\ShopRepository',
        ]);
    }
}
