<?php

namespace ContainerBfPFcOE;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2POTX54Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2POTX54' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2POTX54'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'orepo' => ['privates', 'App\\Repository\\OrderRepository', 'getOrderRepositoryService', true],
            'res' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'orepo' => 'App\\Repository\\OrderRepository',
            'res' => '?',
        ]);
    }
}
