<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Product extends \App\Entity\Product implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'Productname', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'Price', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'oldPrice', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'Productdes', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'Productdate', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'Productquantity', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'Productimage', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'Brandid', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'Orderdetailid', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'Status', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'cartdetail'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'Productname', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'Price', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'oldPrice', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'Productdes', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'Productdate', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'Productquantity', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'Productimage', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'Brandid', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'Orderdetailid', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'Status', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'cartdetail'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Product $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getProductname(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductname', []);

        return parent::getProductname();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductname(string $Productname): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductname', [$Productname]);

        return parent::setProductname($Productname);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', []);

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice(int $Price): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', [$Price]);

        return parent::setPrice($Price);
    }

    /**
     * {@inheritDoc}
     */
    public function getOldPrice(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOldPrice', []);

        return parent::getOldPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setOldPrice(int $oldPrice): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOldPrice', [$oldPrice]);

        return parent::setOldPrice($oldPrice);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductdes(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductdes', []);

        return parent::getProductdes();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductdes(string $Productdes): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductdes', [$Productdes]);

        return parent::setProductdes($Productdes);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductdate(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductdate', []);

        return parent::getProductdate();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductdate(\DateTimeInterface $Productdate): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductdate', [$Productdate]);

        return parent::setProductdate($Productdate);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductquantity(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductquantity', []);

        return parent::getProductquantity();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductquantity(int $Productquantity): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductquantity', [$Productquantity]);

        return parent::setProductquantity($Productquantity);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductimage(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductimage', []);

        return parent::getProductimage();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductimage(string $Productimage): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductimage', [$Productimage]);

        return parent::setProductimage($Productimage);
    }

    /**
     * {@inheritDoc}
     */
    public function getBrandid(): ?\App\Entity\Brand
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBrandid', []);

        return parent::getBrandid();
    }

    /**
     * {@inheritDoc}
     */
    public function setBrandid(?\App\Entity\Brand $Brandid): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBrandid', [$Brandid]);

        return parent::setBrandid($Brandid);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderdetailid(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderdetailid', []);

        return parent::getOrderdetailid();
    }

    /**
     * {@inheritDoc}
     */
    public function addOrderdetailid(\App\Entity\OrderDetail $orderdetailid): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOrderdetailid', [$orderdetailid]);

        return parent::addOrderdetailid($orderdetailid);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOrderdetailid(\App\Entity\OrderDetail $orderdetailid): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOrderdetailid', [$orderdetailid]);

        return parent::removeOrderdetailid($orderdetailid);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(int $Status): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$Status]);

        return parent::setStatus($Status);
    }

    /**
     * {@inheritDoc}
     */
    public function getCartdetail(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCartdetail', []);

        return parent::getCartdetail();
    }

    /**
     * {@inheritDoc}
     */
    public function addCartdetail(\App\Entity\CartDetail $cartdetail): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCartdetail', [$cartdetail]);

        return parent::addCartdetail($cartdetail);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCartdetail(\App\Entity\CartDetail $cartdetail): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCartdetail', [$cartdetail]);

        return parent::removeCartdetail($cartdetail);
    }

}
