<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Customer extends \App\Entity\Customer implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Customer' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Customer' . "\0" . 'Username', '' . "\0" . 'App\\Entity\\Customer' . "\0" . 'Password', '' . "\0" . 'App\\Entity\\Customer' . "\0" . 'CustomerName', '' . "\0" . 'App\\Entity\\Customer' . "\0" . 'Gender', '' . "\0" . 'App\\Entity\\Customer' . "\0" . 'Address', '' . "\0" . 'App\\Entity\\Customer' . "\0" . 'Telephone', '' . "\0" . 'App\\Entity\\Customer' . "\0" . 'Birthday', '' . "\0" . 'App\\Entity\\Customer' . "\0" . 'Email', '' . "\0" . 'App\\Entity\\Customer' . "\0" . 'Cartid', '' . "\0" . 'App\\Entity\\Customer' . "\0" . 'Orderid'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Customer' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Customer' . "\0" . 'Username', '' . "\0" . 'App\\Entity\\Customer' . "\0" . 'Password', '' . "\0" . 'App\\Entity\\Customer' . "\0" . 'CustomerName', '' . "\0" . 'App\\Entity\\Customer' . "\0" . 'Gender', '' . "\0" . 'App\\Entity\\Customer' . "\0" . 'Address', '' . "\0" . 'App\\Entity\\Customer' . "\0" . 'Telephone', '' . "\0" . 'App\\Entity\\Customer' . "\0" . 'Birthday', '' . "\0" . 'App\\Entity\\Customer' . "\0" . 'Email', '' . "\0" . 'App\\Entity\\Customer' . "\0" . 'Cartid', '' . "\0" . 'App\\Entity\\Customer' . "\0" . 'Orderid'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Customer $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername(string $Username): \App\Entity\Customer
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', [$Username]);

        return parent::setUsername($Username);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword(string $Password): \App\Entity\Customer
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$Password]);

        return parent::setPassword($Password);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerName', []);

        return parent::getCustomerName();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerName(string $CustomerName): \App\Entity\Customer
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerName', [$CustomerName]);

        return parent::setCustomerName($CustomerName);
    }

    /**
     * {@inheritDoc}
     */
    public function getGender(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGender', []);

        return parent::getGender();
    }

    /**
     * {@inheritDoc}
     */
    public function setGender(string $Gender): \App\Entity\Customer
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGender', [$Gender]);

        return parent::setGender($Gender);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', []);

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress(string $Address): \App\Entity\Customer
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', [$Address]);

        return parent::setAddress($Address);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephone(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephone', []);

        return parent::getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephone(string $Telephone): \App\Entity\Customer
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephone', [$Telephone]);

        return parent::setTelephone($Telephone);
    }

    /**
     * {@inheritDoc}
     */
    public function getBirthday(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBirthday', []);

        return parent::getBirthday();
    }

    /**
     * {@inheritDoc}
     */
    public function setBirthday(string $Birthday): \App\Entity\Customer
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBirthday', [$Birthday]);

        return parent::setBirthday($Birthday);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail(string $Email): \App\Entity\Customer
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$Email]);

        return parent::setEmail($Email);
    }

    /**
     * {@inheritDoc}
     */
    public function getCartid(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCartid', []);

        return parent::getCartid();
    }

    /**
     * {@inheritDoc}
     */
    public function addCartid(\App\Entity\Cart $cartid): \App\Entity\Customer
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCartid', [$cartid]);

        return parent::addCartid($cartid);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCartid(\App\Entity\Cart $cartid): \App\Entity\Customer
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCartid', [$cartid]);

        return parent::removeCartid($cartid);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderid(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderid', []);

        return parent::getOrderid();
    }

    /**
     * {@inheritDoc}
     */
    public function addOrderid(\App\Entity\Order $orderid): \App\Entity\Customer
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOrderid', [$orderid]);

        return parent::addOrderid($orderid);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOrderid(\App\Entity\Order $orderid): \App\Entity\Customer
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOrderid', [$orderid]);

        return parent::removeOrderid($orderid);
    }

}
