<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHPrVNMR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHPrVNMR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHPrVNMR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHPrVNMR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHPrVNMR\App_KernelDevDebugContainer([
    'container.build_hash' => 'HPrVNMR',
    'container.build_id' => '1f8ef7ca',
    'container.build_time' => 1665928707,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHPrVNMR');
