<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ0S6zRd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ0S6zRd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZ0S6zRd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZ0S6zRd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZ0S6zRd\App_KernelDevDebugContainer([
    'container.build_hash' => 'Z0S6zRd',
    'container.build_id' => '0794b5d5',
    'container.build_time' => 1665490105,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ0S6zRd');
