<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXLEutUT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXLEutUT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXLEutUT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXLEutUT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXLEutUT\App_KernelDevDebugContainer([
    'container.build_hash' => 'XLEutUT',
    'container.build_id' => '2e4bc661',
    'container.build_time' => 1665911976,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXLEutUT');
